### ISSUE TITLE
OctoPrint-Z-Bolt-OctoScreen Not installing

### ISSUE THREAD

**Issue by clue3030** [Z-Bolt/OctoPrint-Z-Bolt-OctoScreen#4]
OctoPrint-Z-Bolt-OctoScreen is not installing, well it installs but it doesn't get activated to use in octoprint. This needs to be corrected please. Thanks

**Comment by JeffB42** [comment]
It worked fine for me.  Are you installing like the readme states?  In OctoPrint, 
1. Click Settings
2. Click Plugin Manager
3. Scroll to the bottom
4. Click Get More
5. In the "from URL" input field, enter https://github.com/Z-Bolt/OctoPrint-Z-Bolt-OctoScreen/archive/master.zip
6. Click Install
7. Restart

Does this still happen?

**Comment by JeffB42** [comment]
There hasn't been a reply to this so I'm closing the ticket.
